### ISSUE TITLE
Consider adding/creating a website

### ISSUE THREAD

**Issue by peregrinogris** [mercadolibre/mesh#12]
Mesh has it's own section under the Chico webpage (http://chico-ui.com.ar/mesh), it'd be useful to have it linked in the Readme.md file.

**Comment by battaglr** [comment]
@peregrinogris, thank you for bringing this up! Sadly that's from a very old version of Mesh. Currently the only thing that we have is [the test page](https://mercadolibre.github.io/mesh/test/test.html).

That said, I agree that having a website may be useful. I'll modify the title of this issue to so we can use it to discuss the creation —or not— of a new website.

**Comment by battaglr** [comment]
I'll close this due to inactivity.

For the time being I think that [the test page](https://mercadolibre.github.io/mesh/test/test.html) should be enough.

Thanks for bringing this up! 😀
