### ISSUE TITLE
Mesh col-offset suggestion

### ISSUE THREAD

**Issue by escudero89** [mercadolibre/mesh#15]
It would be nice to have offset on the columns, as it have the [Bootstrap grid system](http://getbootstrap.com/css/#grid-offsetting).

This way you can avoid having to use empty `mesh-col-X-Y` divs to create empty spaces, and instead use directly `mesh-col-offset-X-Y` in its place.

**Comment by battaglr** [comment]
@escudero89, we have that feature in mind, so thanks for opening the issue, since it will help us track it!

**Comment by juanbrujo** [comment]
this feature will probably **duplicate** mesh's filesize 👀 
just say'in

**Comment by battaglr** [comment]
@juanbrujo, it will in the raw file, but not in the gzip version that we are going to use.

That said, I'm thinking that "push/pull" could be a module that you include only if you need it. I'm starting to think that Mesh needs to be even more modular, something in the line of this [little grid I made](https://github.com/battaglr/griss).

**Comment by battaglr** [comment]
Closing due to #21. 💀
