### ISSUE TITLE
Mesh unavailable on Bower.io

### ISSUE THREAD

**Issue by santiph** [mercadolibre/mesh#18]
Regarding https://github.com/mercadolibre/mesh/releases/tag/v4.2.2
Please consider updating also its bower name, since `mesh` seems to be already taken also there.

**Comment by battaglr** [comment]
Most projects are being moved to npm and leaving Bower behind —including projects like this one that are not written in JavaScript.

I would like to remove support for Bower —I can't remember the last time I used it. Do you think this is something worth keeping, or do you agree with removing it?

**Comment by santiph** [comment]
I might be missing something (which is very likely since I'm not aware of the long term goals for this libraries), but if the fix is just a matter of change the project name, I'd give it a try. At least until other tools (like https://github.com/mercadolibre/generator-chico-theme, which I'm experimenting at the moment ;) ) move from bower to npm. :)

If the effort is bigger than that, then I'd just dismiss this issue since I've found some workarounds to use `mesh 4.2.2` and `chico 2.0.10` anyways

**Comment by battaglr** [comment]
@santiph, I'm just trying to understand if this is something we want to keep supporting or not —regardless the effort (which, you're right, is trivial). 

AFAIK all our OSS libraries are on npm:
- `[mesh](https://www.npmjs.com/package/mesh-grid)`
- `[chico](https://www.npmjs.com/package/chico)`
- `[generator-chico-theme](https://www.npmjs.com/package/generator-chico-theme)`
- `[tiny](https://www.npmjs.com/package/tiny.js)`

Do you think that we should still support Bower considering this? 😀

**Comment by santiph** [comment]
@battaglr What I meant with the generator is it's still relying on Bower.io to handle certain dependencies:
https://github.com/mercadolibre/generator-chico-theme/blob/master/app/templates/_bower.json

But if they're all on npm, maybe a way to rely on it consistently should be discussed instead.

**Comment by battaglr** [comment]
@santiph, Oh, I get it now! Sorry! I'll take a look into that. Thanks!

**Comment by battaglr** [comment]
Done!

You can now install it using: `bower install mesh-grid`.

You could also do it by referencing the GitHub repo as is done in the [generator-chico-theme Bower file](https://github.com/mercadolibre/generator-chico-theme/blob/master/app/templates/_bower.json).

Thanks for reporting this!

---

Resolved by ca76a24eaddc386485a25cf1d8ac48efa6a5319b.
